id: 84a2ef86600041779bf504d42da7c936
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_122-Wisdom_at_the_Hour_of_Death-v1
  language: bo
  author: ''
  volume: {}
